<?php

return [
  'regions' => [
      'central-athens' => [
          "path3900" => "Αθήνα",
          "path5595" => "Δάφνη-Υμηττός",
          "path5653" => "Ηλιούπολη",
          "path5658" => "Βύρωνας",
          "path5666" => "Καισαριανή",
          "path5671" => "Ζωγράφου",
          "path4689" => "Γαλάτσι",
          "path5727" => "Φιλαδέλφεια-Χαλκιδόνα"
      ],
      'west-athens' => [
          "path5797" =>"Αιγάλεο",
          "path5820" =>"Αγία Βαρβάρα",
          "path5792" =>"Χαϊδάρι",
          "path5776" =>"Περιστέρι",
          "path5763" =>"Πετρούπολη",
          "path5756" =>"Ίλιον",
          "path5739" =>"Άγιοι Ανάργυροι-Καματερό"
      ],
      'north-athens' => [
          "path4715" =>"Νέα Ιονία",
          "path3533" =>"Ηράκλειο (Αττικής)",
          "path4745" =>"Μεταμόρφωση",
          "path5578" =>"Λυκόβρυση-Πεύκη",
          "path5858" =>"Κιφισσιά",
          "path5717" =>"Πεντέλη",
          "path5710" =>"Μαρούσι",
          "path5713" =>"Βρυλλήσια",
          "path5722" =>"Αγία Παρασκευή",
          "path5682" =>"Παπάγου-Χολαργός",
          "path5703" =>"Χαλάνδρι",
          "path4685" =>"Φιλοθέη-Ψυχικό"
      ],
      'south-athens' => [
          "path5648" =>"Γλυφάφα",
          "path5642" =>"Ελληνικό-Αργυρούπολη",
          "path5623" =>"Άλιμος",
          "path5609" =>"Άγιος Δημήτριος",
          "path5602" =>"Νέα Σμύρνη",
          "path5616" =>"Παλαιό Φάληρο",
          "path5817" =>"Καλλιθέα",
          "path5814" =>"Μοσχάτο-Ταύρος"
      ],
      'piraeus' =>[
          "Keratsini-Drapetsona",
          "Korydallos",
          "Nikaia-Agios Ioannis Rentis",
          "Perama",
          "temp" => "Πειραιάς"
      ]
  ],
    'paths' => [
        "path3900" => "Athens",
        "path5595" => "Dafni-Ymittos",
        "path5653" => "Ilioupoli",
        "path5658" => "Vyronas",
        "path5666" => "Kaisariani",
        "path5671" => "Zografou",
        "path4689" => "Galatsi",
        "path5727" => "Filadelfeia-Chalkidona",
        "path5648" =>"Glyfada",
        "path5642" =>"Elliniko-Argyroupoli ",
        "path5623" =>"Alimos",
        "path5609" =>"Agios Dimitrios",
        "path5602" =>"Nea Smyrni",
        "path5616" =>"Palaio Faliro",
        "path5817" =>"Kallithea",
        "path5814" =>"Moschato-Tavros",
        "path4715" =>"Nea Ionia",
        "path3533" =>"Irakleio",
        "path4745" =>"Metamorfosi",
        "path5578" =>"Lykovrysi-Pefki",
        "path5858" =>"Kifissia",
        "path5717" =>"Penteli",
        "path5710" =>"Marousi",
        "path5713" =>"Vrilissia",
        "path5722" =>"Agia Paraskevi",
        "path5682" =>"Papagou-Cholargos",
        "path5703" =>"Chalandri",
        "path4685" =>"Filothei-Psychiko",
        "path5797" =>"Egaleo",
        "path5820" =>"Agia Varvara",
        "path5792" =>"Chaidari",
        "path5776" =>"Peristeri",
        "path5763" =>"Petroupoli",
        "path5756" =>"Ilion",
        "path5739" =>"Agioi Anargyroi-Kamatero"
    ],
    'trans' => [
        "path3900" => "ΑΘΗΝΑΙΩΝ",
        "path5595" => "ΔΑΦΝΗΣ-ΥΜΗΤΤΟΥ",
        "path5653" => "ΗΛΙΟΥΠΟΛΕΩΣ",
        "path5658" => "ΒΥΡΩΝΟΣ",
        "path5666" => "ΚΑΙΣΑΡΙΑΝΗΣ",
        "path5671" => "ΖΩΓΡΑΦΟΥ",
        "path4689" => "ΓΑΛΑΤΣΙΟΥ",
        "path5727" => "ΝΕΑΣ ΦΙΛΑΔΕΛΦΕΙΑΣ - ΝΕΑΣ ΧΑΛΚΗΔΟΝΑΣ",
        "path5648" =>"ΓΛΥΦΑΔΑΣ",
        "path5642" =>"ΕΛΛΗΝΙΚΟΥ - ΑΡΓΥΡΟΥΠΟΛΗΣ",
        "path5623" =>"ΑΛΙΜΟΥ",
        "path5609" =>"ΑΓΙΟΥ ΔΗΜΗΤΡΙΟΥ",
        "path5602" =>"ΝΕΑΣ ΣΜΥΡΝΗΣ",
        "path5616" =>"ΠΑΛΑΙΟΥ ΦΑΛΗΡΟΥ",
        "path5817" =>"ΚΑΛΛΙΘΕΑΣ",
        "path5814" =>"ΜΟΣΧΑΤΟΥ-ΤΑΥΡΟΥ",
        "path4715" =>"ΝΕΑΣ ΙΩΝΙΑΣ",
        "path3533" =>"ΗΡΑΚΛΕΙΟΥ ΑΤΤΙΚΗΣ",
        "path4745" =>"ΜΕΤΑΜΟΡΦΩΣΗΣ",
        "path5578" =>"ΛΥΚΟΒΡΥΣΗΣ - ΠΕΥΚΗΣ",
        "path5858" =>"ΚΗΦΙΣΙΑΣ",
        "path5717" =>"ΠΕΝΤΕΛΗΣ",
        "path5710" =>"ΑΜΑΡΟΥΣΙΟΥ",
        "path5713" =>"ΒΡΙΛΗΣΣΙΩΝ",
        "path5722" =>"ΑΓΙΑΣ ΠΑΡΑΣΚΕΥΗΣ",
        "path5682" =>"ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ",
        "path5703" =>"ΧΑΛΑΝΔΡΙΟΥ",
        "path4685" =>"ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ",
        "path5797" =>"ΑΙΓΑΛΕΩ",
        "path5820" =>"ΑΓΙΑΣ ΒΑΡΒΑΡΑΣ",
        "path5792" =>"ΧΑΙΔΑΡΙΟΥ",
        "path5776" =>"ΠΕΡΙΣΤΕΡΙΟΥ",
        "path5763" =>"ΠΕΤΡΟΥΠΟΛΕΩΣ",
        "path5756" =>"ΙΛΙΟΥ (ΝΕΩΝ ΛΙΟΣΙΩΝ)",
        "path5739" =>"ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ"
    ]
];
